# Generated by Django 4.0.3 on 2022-04-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('done', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='Deadline',
            field=models.DateTimeField(default=2),
            preserve_default=False,
        ),
    ]
